# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'rnRouterBoilerPlate' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rnRouterBoilerPlate
  pod 'Firebase/Core'

  target 'rnRouterBoilerPlateTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'rnRouterBoilerPlate-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rnRouterBoilerPlate-tvOS

  target 'rnRouterBoilerPlate-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
